/*
==========================================================================================================================
5. Magnitude Analysis: (Understanding the distribution and importance of different business categories)
==========================================================================================================================
Purpose:
    • Analyze the distribution of customers, products, and sales across categories
    • Measure customer and product volume across different business dimensions
    • Evaluate revenue contribution from customers and product categories
    • Understand sales volume and product distribution patterns
==========================================================================================================================
*/

-- Total number of customers by countries
SELECT
country,
COUNT(customer_key) total_customers
FROM gold.dim_customer_info
GROUP BY country
ORDER BY total_customers DESC;

-- Total number of customers who placed an order by countries
SELECT
country,
COUNT(DISTINCT s.customer_key) total_customers
FROM gold.fact_sales_info s
LEFT JOIN gold.dim_customer_info c
ON s.customer_key = c.customer_key
GROUP BY country
ORDER BY 2 DESC;
-- Note: All customers have placed orders, so, we get same result from above both queries.

-- Total number of customers by gender
SELECT
gender,
COUNT(customer_key) total_customers
FROM gold.dim_customer_info
GROUP BY gender
ORDER BY 2 DESC;

-- Total number of customers by marital status
SELECT
marital_status,
COUNT(customer_key) total_customers
FROM gold.dim_customer_info
GROUP BY marital_status
ORDER BY 2 DESC;

-- Total number of products by categories
SELECT
category,
COUNT(product_key) total_products
FROM gold.dim_product_info
GROUP BY category
ORDER BY 2 DESC;

-- Average cost of each category
SELECT
category,
AVG(cost) avg_cost
FROM gold.dim_product_info
GROUP BY category
ORDER BY 2 DESC;

-- Total revenue generated by each customer
SELECT
c.customer_key,
c.first_name + ' ' + c.last_name customer_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales_info s
LEFT JOIN gold.dim_customer_info c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY 3 DESC;

-- Distribution of sold items across countries
SELECT
c.country,
SUM(s.quantity) total_sold_items
FROM gold.fact_sales_info s
LEFT JOIN gold.dim_customer_info c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY 2 DESC;

-- Total revenue generated by categories
SELECT
p.category,
SUM(s.sales_amount) total_sales
FROM gold.fact_sales_info s
LEFT JOIN gold.dim_product_info p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY 2 DESC;

-- Total number of products sold from categories, sub-categories
SELECT
category,
subcategory,
SUM(quantity) total_products   -- Total quantity across all products
FROM gold.fact_sales_info s
LEFT JOIN gold.dim_product_info p
ON s.product_key = p.product_key
GROUP BY category, subcategory
ORDER BY 1, 2;