/*
=============================================================================================================================
Script: Create Report View for Product Insights
=============================================================================================================================
Objective: This report provides insights into product performance.

This script performs the following operations:
1. Gather essential fields such as product names, categories, subcategories, costs, and transaction details.
2. Aggregate data to compute total orders, customers, quantity, and sales for each product.
3. Calculate product age, lifespan, and last order date to understand product lifecycle.
4. Product Segmentation: 
    - Classifies products into Best-Seller, Steady-Performer, and Slow-Mover based on total sales.
    - Categorizes products into cost groups for pricing analysis.
5. Key Metrics:
    - Recency Analysis: Measures how recently products have been sold to identify active vs. dormant products.
    - Average Order Revenue: Calculates the average revenue generated per order for each product.
    - Average Monthly Revenue: Evaluates the average monthly revenue generated by products to understand sales trends.
6. This report provides a comprehensive view of product performance, including metrics, segmentation, and lifecycle insights.

Usage: This view can be used to analyze product performance, identify trends, and make informed decisions regarding 
inventory management, marketing strategies, and product development.
=============================================================================================================================
*/

--->>> Create Report View: gold.report_product_info
IF OBJECT_ID ('gold.report_product_info', 'V') IS NOT NULL
    DROP VIEW gold.report_product_info;
GO

CREATE VIEW gold.report_product_info AS
    WITH product_details AS
    (
    SELECT
        s.order_id,
        s.customer_key,
        s.sales_amount,
        s.quantity,
        s.order_date,
        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost,
        p.start_date
    FROM gold.fact_sales_info s
    LEFT JOIN gold.dim_product_info p
    ON s.product_key = p.product_key
    ),

    product_details_aggregation AS
    (
    SELECT
        product_key,
        product_name,
        category,
        subcategory,
        DATEDIFF(YEAR, start_date, GETDATE()) AS product_age,
        cost,   -- Product cost is constant in dataset
        COUNT(DISTINCT order_id) AS total_orders,
        COUNT(DISTINCT customer_key) AS total_customers,
        SUM(quantity) AS total_quantity,
        SUM(sales_amount) AS total_sales,
        MIN(order_date) AS first_sale_date,
        MAX(order_date) AS last_sale_date,
        DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan_months,
        CAST(SUM(sales_amount)*1.0 / SUM(quantity) AS DECIMAL(10,2)) avg_selling_price   --ALTERNATE: CAST(AVG(sales_amount*1.0 / NULLIF(quantity, 0)) AS DECIMAL(10,2))
    FROM product_details
    GROUP BY product_key, product_name, category, subcategory, start_date, cost
    )

    SELECT
        product_key,
        product_name,
        category,
        subcategory,
        product_age,
        cost,
        CASE WHEN cost < 100 THEN 'Below 100'
             WHEN cost BETWEEN 100 AND 500 THEN '100-500'
             WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
             ELSE 'Above 1000' END AS cost_group,
        CASE WHEN total_sales > 50000 THEN 'Best-Seller'
             WHEN total_sales BETWEEN 5000 AND 10000 THEN 'Steady-Performer'
             ELSE 'Slow-Mover' END AS product_segment,
        total_orders,
        total_customers,
        total_quantity,
        total_sales,
        avg_selling_price,
        lifespan_months,
        last_sale_date,
        DATEDIFF(MONTH, last_sale_date, GETDATE()) AS recency_in_months,   -- Months since last order (Customer Inactivity)
        total_sales / NULLIF(total_orders, 0) AS avg_order_revenue,
        CASE WHEN lifespan_months = 0 THEN total_sales
             ELSE total_sales / lifespan_months END AS avg_monthly_revenue
    FROM product_details_aggregation;
GO